version: "3"
services:
  bot:
    image: ottersprod/otters-discord:${GIT_COMMIT_HASH:-latest}
    restart: unless-stopped
    secrets:
      - discord_token
      - openai_key

secrets:
  discord_token:
    external: true
  openai_key:
    external: true
