export enum Job {
  NIGHT_LORD = "NIGHT_LORD",
  SHADOWER = "SHADOWER",
  BOWMASTER = "BOWMASTER",
  MARKSMAN = "MARKSMAN",
  CORSAIR = "CORSAIR",
  BUCCANEER = "BUCCANEER",
  HERO = "HERO",
  DARK_KNIGHT = "DARK_KNIGHT",
  PALADIN = "PALADIN",
  MAGICIAN = "MAGICIAN",
  BEGINNER = "BEGINNER",
}

export const WARRIOR = [Job.DARK_KNIGHT, Job.PALADIN, Job.HERO];
export const THIEF = [Job.NIGHT_LORD, Job.SHADOWER];
export const PIRATE = [Job.CORSAIR, Job.BUCCANEER];
