name: Publish to docker hub

on:
  push:
    branches:
      - master

jobs:
  build-push-story:
    runs-on: ubuntu-latest
    name: Deploy otters-story
    on:
      push:
        paths:
          - "**"
          - "!.github/**"
          - "!*.md"
          - "!bots/**"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Otters Story
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=gha,scope=story
          cache-to: type=gha,scope=story,mode=max
          tags: |
            ottersprod/otters-story:latest
            ottersprod/otters-story:${{ github.sha }}

  build-push-bot:
    runs-on: ubuntu-latest
    name: Deploy otters-bot
    on:
      push:
        paths:
          - "bots/**"
          - "!.github/**"
          - "!*.md"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Otters Bot
        uses: docker/build-push-action@v5
        with:
          context: ./bots/discord
          file: ./bots/discord/Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=gha,scope=bot
          cache-to: type=gha,scope=bot,mode=max
          tags: |
            ottersprod/otters-discord:latest
            ottersprod/otters-discord:${{ github.sha }}

  deploy-story:
    runs-on: ubuntu-latest
    needs:
      - build-push-story
    on:
      push:
        paths:
          - "**"
          - "!.github/**"
          - "!*.md"
          - "!bots/**"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy Story
        uses: cssnr/stack-deploy-action@v1
        with:
          name: otterstory
          file: docker-stack.yaml
          host: ${{ secrets.IP}}
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile

  deploy-bot:
    runs-on: ubuntu-latest
    needs:
      - build-push-bot
    on:
      push:
        paths:
          - "bots/**"
          - "!.github/**"
          - "!*.md"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy Bot
        uses: cssnr/stack-deploy-action@v1
        with:
          name: otterbot
          file: ./bots/discord/docker-stack.yaml
          host: ${{ secrets.IP}}
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
