name: Publish to docker hub

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      bots_changed: ${{ steps.filter.outputs.bots }}
      main_changed: ${{ steps.filter.outputs.main }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            bots:
              - 'bots/**'
            main:
              - '**'
              - '!bots/**'

  build-push:
    runs-on: ubuntu-latest
    name: Deploy otters-story
    needs: check-changes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Otters Story
        if: needs.check-changes.outputs.main_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ottersprod/otters-story:latest
            ottersprod/otters-story:${{ github.sha }}

      - name: Build and push Otters Bot
        if: needs.check-changes.outputs.bots_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./bots/discord
          file: ./bots/discord/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ottersprod/otters-discord:latest
            ottersprod/otters-discord:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: otterstory
          file: docker-stack.yaml
          host: ${{ secrets.IP}}
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
